Hw01
================
Dominique Tzou
2026-09-26

``` r
library(tidyverse) #loading in tidyverse, to use the pull function later
```

    ## ── Attaching core tidyverse packages ──────────────────────── tidyverse 2.0.0 ──
    ## ✔ dplyr     1.2.1     ✔ readr     2.2.0
    ## ✔ forcats   1.0.1     ✔ stringr   1.6.0
    ## ✔ ggplot2   4.0.3     ✔ tibble    3.3.1
    ## ✔ lubridate 1.9.5     ✔ tidyr     1.3.2
    ## ✔ purrr     1.2.2     
    ## ── Conflicts ────────────────────────────────────────── tidyverse_conflicts() ──
    ## ✖ dplyr::filter() masks stats::filter()
    ## ✖ dplyr::lag()    masks stats::lag()
    ## ℹ Use the conflicted package (<http://conflicted.r-lib.org/>) to force all conflicts to become errors

# Problem 1

``` r
data("penguins", package = "palmerpenguins") #Loading in penguins dataset
penguins = janitor::clean_names(penguins) #cleaning names
```

## Summary of the penguin dataset and variables

|                                                  |          |
|:-------------------------------------------------|:---------|
| Name                                             | penguins |
| Number of rows                                   | 344      |
| Number of columns                                | 8        |
| \_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_   |          |
| Column type frequency:                           |          |
| factor                                           | 3        |
| numeric                                          | 5        |
| \_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_ |          |
| Group variables                                  | None     |

Data summary

**Variable type: factor**

| skim_variable | n_missing | complete_rate | ordered | n_unique | top_counts |
|:---|---:|---:|:---|---:|:---|
| species | 0 | 1.00 | FALSE | 3 | Ade: 152, Gen: 124, Chi: 68 |
| island | 0 | 1.00 | FALSE | 3 | Bis: 168, Dre: 124, Tor: 52 |
| sex | 11 | 0.97 | FALSE | 2 | mal: 168, fem: 165 |

**Variable type: numeric**

| skim_variable | n_missing | complete_rate | mean | sd | p0 | p25 | p50 | p75 | p100 | hist |
|:---|---:|---:|---:|---:|---:|---:|---:|---:|---:|:---|
| bill_length_mm | 2 | 0.99 | 43.92 | 5.46 | 32.1 | 39.23 | 44.45 | 48.5 | 59.6 | ▃▇▇▆▁ |
| bill_depth_mm | 2 | 0.99 | 17.15 | 1.97 | 13.1 | 15.60 | 17.30 | 18.7 | 21.5 | ▅▅▇▇▂ |
| flipper_length_mm | 2 | 0.99 | 200.92 | 14.06 | 172.0 | 190.00 | 197.00 | 213.0 | 231.0 | ▂▇▃▅▂ |
| body_mass_g | 2 | 0.99 | 4201.75 | 801.95 | 2700.0 | 3550.00 | 4050.00 | 4750.0 | 6300.0 | ▃▇▆▃▂ |
| year | 0 | 1.00 | 2008.03 | 0.82 | 2007.0 | 2007.00 | 2008.00 | 2009.0 | 2009.0 | ▇▁▇▁▇ |

Some additional details

- Variables: Variable names include species, island, bill_length_mm,
  bill_depth_mm, flipper_length_mm, body_mass_g, sex, year

- Years: The data spans from Year 2007 to 2009

- Size: The size of the penguins dataset includes 344 rows and 8
  columns.

- The mean flipper length is 200.92 mm.

### Scatterplot of flipper_length_mm (y) vs bill_length_mm (x)

``` r
ggplot(penguins, aes(x = bill_length_mm,  y = flipper_length_mm, color = species))+geom_point()
```

    ## Warning: Removed 2 rows containing missing values or values outside the scale range
    ## (`geom_point()`).

![](p8105_hw1_dt2833_files/figure-gfm/scatterplot-1.png)<!-- -->

``` r
ggsave("hw01_scatterplot.png")
```

    ## Saving 7 x 5 in image

    ## Warning: Removed 2 rows containing missing values or values outside the scale range
    ## (`geom_point()`).

# Problem 2

### Creating a dataframe

``` r
# setting seed to ensure reproducibility
set.seed(4321)

prob2_df = tibble(
  norm_samp = rnorm(10),#a random sample of size 10 from a standard Normal distribution
  norm_samp_pos = norm_samp > 0, #a logical vector indicating whether elements of the sample are greater than 0
  vec_char = c("cake","cookies", "crepes", "croissants", "creampuff", "cannolli", "cheesecake", "cupcake", "crumble", "cobbler" ), #a character vector of length 10 desserts
  vec_factor = factor(c("good", "better", "best", "good", "better", "best", "good", "better", "best", "best")) #a factor vector of length 10, with 3 different factor “levels": good, better, best
)

#taking the mean of each 4 variables
mean_norm_samp = mean(pull(prob2_df, norm_samp))
mean_samp_pos = mean(pull(prob2_df, norm_samp_pos))
mean_vec_char = mean(pull(prob2_df, vec_char))
```

    ## Warning in mean.default(pull(prob2_df, vec_char)): argument is not numeric or
    ## logical: returning NA

``` r
mean_vec_factor = mean(pull(prob2_df, vec_factor))
```

    ## Warning in mean.default(pull(prob2_df, vec_factor)): argument is not numeric or
    ## logical: returning NA

### Mean results of variables

The mean for the sample is 0.2811. This works because it is a numerical
variable.

The mean for the logical vector indicating whether elements of the
sample are greater than 0 is 0.5. This works because it is a numerical
variable.

The mean for the character vector is NA. This does not works because it
is a character variable.

The mean for the factor vector is NA. This does not works because it is
a character/factor variable.

### Attempting to convert character variables into numeric

``` r
as.numeric(pull(prob2_df,norm_samp_pos))
as.numeric(pull(prob2_df,vec_char))
as.numeric(pull(prob2_df,vec_factor))
```

When applying the as.numeric function to the logical and factor
variables, their output categories (often repeated in the dataframe) are
converted/designated to numerical values, so that a mean can be taken.
But when as.numeric function is applied to the character variable, it is
unsuccessful, but of its unique character values. A mean cannot be
calculated.
